server:
  port: 8700
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          # 这里填写的是本地仓库地址，远程仓库直接填写远程仓库地址 http://git...
          uri: https://github.com/llzblzb/SpringCloudStudy.git
          # 默认分支设定为你自己本地或是远程分支的名称
          default-label: main
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8801/eureka ,http://localhost:8802/eureka